---
- name: Ensure Jellyfin directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: core
    group: core
    mode: '0700'
  loop:
    - /mnt/fast/jellyfin/config
    - /mnt/fast/jellyfin/cache

- name: Ensure Jellyfin image is present
  containers.podman.podman_image:
    name: ghcr.io/jellyfin/jellyfin:latest
    state: present
    pull: true
  notify: Restart Jellyfin service

- name: Ensure Jellyfin Quadlet is defined
  containers.podman.podman_container:
    name: jellyfin
    state: quadlet
    image: ghcr.io/jellyfin/jellyfin:latest
    env:
      TZ: Europe/Tallinn
      JELLYFIN_DATA_DIR: /config
      JELLYFIN_CONFIG_DIR: /config/config
      JELLYFIN_CACHE_DIR: /cache
      JELLYFIN_WEB_DIR: /jellyfin/jellyfin-web
      JELLYFIN_LOG_DIR: /config/log
      # JELLYFIN_FFMPEG: /usr/lib/jellyfin-ffmpeg/ffmpeg
      # JELLYFIN_hostwebclient: true
      # JELLYFIN_FFmpeg__probesize: "1G"
      # JELLYFIN_FFmpeg__analyzeduration: "200M"
      JELLYFIN_PublishedServerUrl: https://jellyfin.cormo-tegu.ts.net
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    mount:
      - type=tmpfs,destination=/run,U=true,exec
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/jellyfin/config:/config
      - /mnt/fast/jellyfin/cache:/cache
      - /mnt/slow:/media
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    group_add:
      - keep-groups
    security_opt:
      - no-new-privileges
    memory: 4G
    pids_limit: '512'
    cpus: '4'
    device:
      - /dev/dri/card0:/dev/dri/card0
      - /dev/dri/renderD128:/dev/dri/renderD128
    healthcheck: curl --noproxy localhost -Lk -fsS http://127.0.0.1:8096/health || exit 1
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Jellyfin service
