---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.4.9
  - name: containers.podman
    version: 1.20.2
  - name: fedora.linux_system_roles
    version: 1.127.2
