---
- name: Ensure Recyclarr directory exists
  ansible.builtin.file:
    path: /mnt/fast/recyclarr/config
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Recyclarr configuration is deployed
  ansible.builtin.copy:
    src: recyclarr.yml
    dest: /mnt/fast/recyclarr/config/recyclarr.yml
    owner: core
    group: core
    mode: '0600'
  notify: Restart Recyclarr service

- name: Ensure Recyclarr image is present
  containers.podman.podman_image:
    name: ghcr.io/recyclarr/recyclarr:8
    state: present
    pull: true
  notify: Restart Recyclarr service

- name: Ensure Recyclarr Quadlet is defined
  containers.podman.podman_container:
    name: recyclarr
    state: quadlet
    image: ghcr.io/recyclarr/recyclarr:8
    env:
      CRON_SCHEDULE: 0 4 * * *
      TZ: Europe/Tallinn
      # RECYCLARR_CREATE_CONFIG: false
      # RECYCLARR_CONFIG_DIR: /config
      # RECYCLARR_DATA_DIR: /config
      # NO_COLOR: ''
    secrets:
      - radarr_api_key,type=mount,target=/run/secrets/radarr_api_key,uid=1000,gid=1000,mode=0400
      - sonarr_api_key,type=mount,target=/run/secrets/sonarr_api_key,uid=1000,gid=1000,mode=0400
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    mount:
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/recyclarr/config:/config
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
    memory: 512M
    pids_limit: '256'
    cpus: '1'
    healthcheck: pidof supercronic >/dev/null && recyclarr --version >/dev/null || exit 1
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Recyclarr service
