---
- name: Ensure Zerobyte directory exists
  ansible.builtin.file:
    path: /mnt/fast/zerobyte/data
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Zerobyte application secret is present
  containers.podman.podman_secret:
    name: zerobyte_app_secret
    data: '{{ zerobyte_app_secret }}'
    state: present
    force: true
  no_log: true
  notify: Restart Zerobyte service

- name: Ensure Zerobyte image is present
  containers.podman.podman_image:
    name: ghcr.io/nicotsx/zerobyte:latest
    state: present
    pull: true
  notify: Restart Zerobyte service

- name: Ensure Zerobyte Quadlet is defined
  containers.podman.podman_container:
    name: zerobyte
    state: quadlet
    hostname: homelab
    image: ghcr.io/nicotsx/zerobyte:latest
    env:
      TZ: Europe/Tallinn
      BASE_URL: https://zerobyte.cormo-tegu.ts.net
      APP_SECRET_FILE: /run/secrets/zerobyte_app_secret
    secrets:
      - zerobyte_app_secret,type=mount,target=/run/secrets/zerobyte_app_secret,uid=1000,gid=1000,mode=0400
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    volume:
      - /mnt/fast/zerobyte/data:/var/lib/zerobyte
      - /mnt/slow:/mnt/slow:ro
      - /mnt/fast:/mnt/fast:ro
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
      - label=disable
    memory: 2G
    pids_limit: '512'
    cpus: '2'
    healthcheck: wget -qO- http://127.0.0.1:4096/api/healthcheck >/dev/null || exit 1
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Zerobyte service
