services:
  borgmatic:
    container_name: borgmatic
    hostname: homelab
    image: ghcr.io/borgmatic-collective/borgmatic:2.1.6@sha256:c83845639775392a782e3290ebd7b09285f56b6d9e1fcf7874c4ed99512120ca
    restart: unless-stopped
    mem_limit: 2g
    pids_limit: 512
    cpus: 2
    environment:
      BACKUP_CRON: 0 22 * * *
      TZ: Europe/Tallinn
      BORG_PASSCOMMAND: cat /run/secrets/borg_passphrase
    secrets:
      - source: borg_passphrase
        target: /run/secrets/borg_passphrase
        mode: 0400
      - source: borgmatic_ssh_key
        target: /root/.ssh/id_ed25519
        mode: 0400
      - source: borgmatic_config
        target: /etc/borgmatic.d/config.yaml
        mode: 0400
      - source: immich_db_password
        target: /run/secrets/immich_db_password
        mode: 0400
    security_opt:
      - label=disable
    volumes:
      - borgmatic-config:/root/.config/borg:Z
      - borgmatic-cache:/root/.cache/borg:Z
      - borgmatic-state:/root/.local/state/borgmatic:Z
      - ./known_hosts:/root/.ssh/known_hosts:ro
      - /mnt/media:/mnt/source/media:ro
      - /mnt/extra1/downloads:/mnt/source/extra1/downloads:ro
      - /mnt/extra2/movies:/mnt/source/extra2/movies:ro
      - tailscale:/mnt/source/tailscale:ro
      - uptime-kuma:/mnt/source/uptime-kuma:ro
      - bichon:/mnt/source/bichon:ro
      - immich-library:/mnt/source/immich:ro
      - jellyfin-config:/mnt/source/jellyfin:ro
      - transmission:/mnt/source/transmission:ro
      - prowlarr:/mnt/source/prowlarr:ro
      - radarr:/mnt/source/radarr:ro
      - sonarr:/mnt/source/sonarr:ro
      - recyclarr:/mnt/source/recyclarr:ro
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "pidof crond >/dev/null && borgmatic config validate >/dev/null || exit 1"]

secrets:
  borg_passphrase:
    file: ../secrets/borg_passphrase
  borgmatic_ssh_key:
    file: ../secrets/borgmatic_id_ed25519
  borgmatic_config:
    file: ../secrets/borgmatic_config.yaml
  immich_db_password:
    file: ../secrets/immich_db_password

volumes:
  borgmatic-config:
    name: borgmatic-config
  borgmatic-cache:
    name: borgmatic-cache
  borgmatic-state:
    name: borgmatic-state
  tailscale:
    external: true
    name: tailscale
  uptime-kuma:
    external: true
    name: uptime-kuma
  bichon:
    external: true
    name: bichon
  immich-library:
    external: true
    name: immich-library
  jellyfin-config:
    external: true
    name: jellyfin-config
  transmission:
    external: true
    name: transmission
  prowlarr:
    external: true
    name: prowlarr
  radarr:
    external: true
    name: radarr
  sonarr:
    external: true
    name: sonarr
  recyclarr:
    external: true
    name: recyclarr

networks:
  proxy:
    name: proxy
