---
- name: Ensure Radarr directory exists
  ansible.builtin.file:
    path: /mnt/fast/radarr/config
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Radarr image is present
  containers.podman.podman_image:
    name: lscr.io/linuxserver/radarr:latest
    state: present
    pull: true
    auth_file: /home/core/.config/containers/auth.json
  notify: Restart Radarr service

- name: Ensure Radarr Quadlet is defined
  containers.podman.podman_container:
    name: radarr
    state: quadlet
    image: lscr.io/linuxserver/radarr:latest
    label:
      io.containers.autoupdate: registry
    memory: 1G
    pids_limit: '256'
    cpus: '2'
    env:
      TZ: Europe/Tallinn
    userns: keep-id:uid=1000,gid=1000
    read_only: true
    security_opt:
      - no-new-privileges
    mount:
      - type=tmpfs,destination=/run,U=true,exec
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/radarr/config:/config
      - /mnt/slow:/data
    network:
      - proxy.network
    healthcheck: curl -fsS http://127.0.0.1:7878/ >/dev/null || exit 1
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
    user: 1000:1000
    restart_policy: always
  notify: Restart Radarr service
