services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:10.11.11@sha256:45f648c382a0c8b552582fcea40e95cb17c5d475473a891cba0eb7523fb92112
    restart: unless-stopped
    mem_limit: 4g
    pids_limit: 512
    cpus: 4
    user: "1000:1000"
    userns_mode: keep-id
    group_add:
      - keep-groups
    read_only: true
    security_opt:
      - no-new-privileges:true
    volumes:
      - jellyfin-config:/config:Z,U
      - jellyfin-cache:/cache:Z,U
      - /mnt/extra2/movies:/media/movies:z
      - /mnt/media/shows:/media/shows:z
    devices:
      - /dev/dri:/dev/dri
    networks:
      - proxy
    healthcheck:
      test: ["CMD-SHELL", "curl --noproxy localhost -Lk -fsS http://127.0.0.1:8096/health || exit 1"]

volumes:
  jellyfin-config:
    name: jellyfin-config
  jellyfin-cache:
    name: jellyfin-cache

networks:
  proxy:
    name: proxy
