---
- name: Ensure Uptime Kuma directory exists
  ansible.builtin.file:
    path: /mnt/fast/uptime-kuma/data
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Uptime Kuma image is present
  containers.podman.podman_image:
    name: dhi.io/uptime-kuma:2
    state: present
    pull: true
  notify: Restart Uptime Kuma service

- name: Ensure Uptime Kuma Quadlet is defined
  containers.podman.podman_container:
    name: uptime-kuma
    state: quadlet
    image: dhi.io/uptime-kuma:2
    label:
      io.containers.autoupdate: registry
    memory: 1G
    pids_limit: '256'
    cpus: '1'
    userns: keep-id:uid=1000,gid=1000
    read_only: true
    security_opt:
      - no-new-privileges
      - label=disable
    volume:
      - '%t/podman/podman.sock:/var/run/docker.sock:ro'
      - /mnt/fast/uptime-kuma/data:/app/data
    network:
      - proxy.network
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
    user: 1000:1000
    restart_policy: always
  notify: Restart Uptime Kuma service
