---
- name: Ensure Uptime Kuma directory exists
  ansible.builtin.file:
    path: /mnt/fast/uptime-kuma/data
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Uptime Kuma image is present
  containers.podman.podman_image:
    name: dhi.io/uptime-kuma:2
    state: present
    pull: true
  notify: Restart Uptime Kuma service

- name: Ensure Uptime Kuma Quadlet is defined
  containers.podman.podman_container:
    name: uptime-kuma
    state: quadlet
    image: dhi.io/uptime-kuma:2
    env:
      DATA_DIR: /app/data
      # UPTIME_KUMA_HOST: '::'
      # HOST: '::'
      # UPTIME_KUMA_PORT: 3001
      # PORT: 3001
      # UPTIME_KUMA_SSL_KEY: ''
      # SSL_KEY: ''
      # UPTIME_KUMA_SSL_CERT: ''
      # SSL_CERT: ''
      # UPTIME_KUMA_SSL_KEY_PASSPHRASE: ''
      # SSL_KEY_PASSPHRASE: ''
      # UPTIME_KUMA_CLOUDFLARED_TOKEN: ''
      # UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN: false
      # UPTIME_KUMA_WS_ORIGIN_CHECK: cors-like
      # UPTIME_KUMA_ALLOW_ALL_CHROME_EXEC: 0
      # UPTIME_KUMA_SQLITE_SINGLE_CONNECTION: true
      # NODE_EXTRA_CA_CERTS: ''
      # NODE_TLS_REJECT_UNAUTHORIZED: 0
      # NODE_OPTIONS: ''
      # NOTIFICATION_PROXY: ''
      # UPTIME_KUMA_DB_TYPE: sqlite
      # UPTIME_KUMA_DB_HOSTNAME: ''
      # UPTIME_KUMA_DB_PORT: 3306
      # UPTIME_KUMA_DB_SOCKET: ''
      # UPTIME_KUMA_DB_POOL_MAX_CONNECTIONS: 10
      # UPTIME_KUMA_DB_NAME: ''
      # UPTIME_KUMA_DB_USERNAME: ''
      # UPTIME_KUMA_DB_PASSWORD: ''
      # UPTIME_KUMA_DB_SSL: false
      # UPTIME_KUMA_DB_CA: ''
      # UPTIME_KUMA_DB_PASSWORD_FILE: ''
      # UPTIME_KUMA_DB_USERNAME_FILE: ''
      # UPTIME_KUMA_DB_CA_FILE: ''
      # NODE_ENV: production
      # UPTIME_KUMA_LOG_RESPONSE_BODY_MONITOR_ID: ''
      # UPTIME_KUMA_HIDE_LOG: ''
      # UPTIME_KUMA_LOG_FORMAT: ''
      # SQL_LOG: 0
      # UPTIME_KUMA_ENABLE_EMBEDDED_MARIADB: 0
      # UPTIME_KUMA_IN_CONTAINER: ''
      # UPTIME_KUMA_DEBUG_INSPECTOR: 0
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    volume:
      - /mnt/fast/uptime-kuma/data:/app/data
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
    memory: 1G
    pids_limit: '256'
    cpus: '1'
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Uptime Kuma service
