---
- name: Ensure Transmission directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: core
    group: core
    mode: '0700'
  loop:
    - /mnt/fast/transmission/config
    - /mnt/fast/transmission/watch

- name: Ensure Transmission secrets are present
  containers.podman.podman_secret:
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    state: present
    force: true
  loop:
    - name: transmission_username
      data: '{{ transmission_rpc_username }}'
    - name: transmission_password
      data: '{{ transmission_password }}'
  loop_control:
    label: '{{ item.name }}'
  no_log: true
  notify: Restart Transmission service

- name: Ensure Transmission configuration is deployed
  ansible.builtin.copy:
    src: settings.json
    dest: /mnt/fast/transmission/config/settings.json
    owner: core
    group: core
    mode: '0600'
  no_log: true
  notify: Restart Transmission service

- name: Ensure Transmission image is present
  containers.podman.podman_image:
    name: lscr.io/linuxserver/transmission:latest
    state: present
    pull: true
  notify: Restart Transmission service

- name: Ensure Transmission Quadlet is defined
  containers.podman.podman_container:
    name: transmission
    state: quadlet
    image: lscr.io/linuxserver/transmission:latest
    env:
      # PUID: 1000
      # PGID: 1000
      TZ: Europe/Tallinn
      # TRANSMISSION_WEB_HOME: ''
      FILE__USER: /run/secrets/transmission_username
      FILE__PASS: /run/secrets/transmission_password
      # WHITELIST: ''
      # PEERPORT: 51413
      # HOST_WHITELIST: ''
      # UMASK: '022'
    secrets:
      - transmission_username,type=mount,target=/run/secrets/transmission_username,uid=1000,gid=1000,mode=0400
      - transmission_password,type=mount,target=/run/secrets/transmission_password,uid=1000,gid=1000,mode=0400
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    mount:
      - type=tmpfs,destination=/run,U=true,exec
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/transmission/config:/config
      - /mnt/fast/transmission/watch:/watch
      - /mnt/slow:/data
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
    memory: 1G
    pids_limit: '256'
    cpus: '2'
    healthcheck: curl -fsS -u "$(cat /run/secrets/transmission_username):$(cat /run/secrets/transmission_password)" http://127.0.0.1:9091/transmission/web/ >/dev/null || exit 1
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Transmission service
