---
- name: Ensure Transmission directory exists
  ansible.builtin.file:
    path: /mnt/fast/transmission/config
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Transmission password secret is present
  containers.podman.podman_secret:
    name: transmission_password
    data: '{{ transmission_password }}'
    state: present
    force: true
  no_log: true
  notify: Restart Transmission service

- name: Ensure Transmission image is present
  containers.podman.podman_image:
    name: lscr.io/linuxserver/transmission:latest
    state: present
    pull: true
  notify: Restart Transmission service

- name: Ensure Transmission Quadlet is defined
  containers.podman.podman_container:
    name: transmission
    state: quadlet
    image: lscr.io/linuxserver/transmission:latest
    env:
      TZ: Europe/Tallinn
      USER: karl
      FILE__PASS: /run/secrets/transmission_password
    secrets:
      - transmission_password,type=mount,target=/run/secrets/transmission_password,uid=1000,gid=1000,mode=0400
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    mount:
      - type=tmpfs,destination=/run,U=true,exec
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/transmission/config:/config
      - /mnt/slow:/data
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
    memory: 1G
    pids_limit: '256'
    cpus: '2'
    healthcheck: curl -fsS -u "$USER:$(cat /run/secrets/transmission_password)" http://127.0.0.1:9091/transmission/web/ >/dev/null || exit 1
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Transmission service
