---
- name: Ensure Tailscale directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: core
    group: core
    mode: '0700'
  loop:
    - /mnt/fast/tailscale/config
    - /mnt/fast/tailscale/data

- name: Ensure Tailscale OAuth secret is present
  containers.podman.podman_secret:
    name: tailscale_oauth_secret
    data: '{{ tailscale_oauth_secret }}'
    state: present
    force: true
  no_log: true
  notify: Restart Tailscale service

- name: Ensure Tailscale configuration is deployed
  ansible.builtin.copy:
    src: serve.json
    dest: /mnt/fast/tailscale/config/serve.json
    owner: core
    group: core
    mode: '0600'
  notify: Restart Tailscale service

- name: Ensure Tailscale image is present
  containers.podman.podman_image:
    name: dhi.io/tailscale:1
    state: present
    pull: true
  notify: Restart Tailscale service

- name: Ensure Tailscale Quadlet is defined
  containers.podman.podman_container:
    name: tailscale
    state: quadlet
    image: dhi.io/tailscale:1
    env:
      # TS_ACCEPT_DNS: ''
      # TS_AUDIENCE: ''
      TS_AUTH_ONCE: 'true'
      TS_AUTHKEY: file:/run/secrets/tailscale_oauth_secret
      # TS_CLIENT_ID: ''
      # TS_CLIENT_SECRET: ''
      # TS_DEST_IP: ''
      TS_ENABLE_HEALTH_CHECK: 'true'
      # TS_ENABLE_METRICS: 'false'
      # TS_HEALTHCHECK_ADDR_PORT: ''
      TS_HOSTNAME: proxy
      # TS_ID_TOKEN: ''
      # TS_KUBE_SECRET: tailscale
      # TS_LOCAL_ADDR_PORT: '[::]:9002'
      # TS_OUTBOUND_HTTP_PROXY_LISTEN: ''
      # TS_ROUTES: ''
      TS_SERVE_CONFIG: /config/serve.json
      # TS_SOCKET: /tmp/tailscaled.sock
      # TS_SOCKS5_SERVER: ''
      TS_STATE_DIR: /var/lib/tailscale
      # TS_TAILNET_TARGET_FQDN: ''
      # TS_TAILNET_TARGET_IP: ''
      TS_USERSPACE: 'true'
      TS_EXTRA_ARGS: --advertise-tags=tag:container
      # TS_TAILSCALED_EXTRA_ARGS: ''
      # TS_EXPERIMENTAL_SERVICE_AUTO_ADVERTISEMENT: 'true'
    secrets:
      - tailscale_oauth_secret,type=mount,target=/run/secrets/tailscale_oauth_secret,uid=1000,gid=1000,mode=0400
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    tmpfs:
      /tmp: rw,nosuid,nodev,mode=1777
      /run: rw,nosuid,nodev,mode=755
    volume:
      - /mnt/fast/tailscale/data:/var/lib/tailscale
      - /mnt/fast/tailscale/config/serve.json:/config/serve.json:ro
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
    memory: 512M
    pids_limit: '256'
    cpus: '1'
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Tailscale service
