---
- name: Ensure Prowlarr directory exists
  ansible.builtin.file:
    path: /mnt/fast/prowlarr/config
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Prowlarr image is present
  containers.podman.podman_image:
    name: lscr.io/linuxserver/prowlarr:latest
    state: present
    pull: true
  notify: Restart Prowlarr service

- name: Ensure Prowlarr Quadlet is defined
  containers.podman.podman_container:
    name: prowlarr
    state: quadlet
    image: lscr.io/linuxserver/prowlarr:latest
    env:
      TZ: Europe/Tallinn
    label:
      io.containers.autoupdate: registry
    network:
      - proxy.network
    mount:
      - type=tmpfs,destination=/run,U=true,exec
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/prowlarr/config:/config
    read_only: true
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
    memory: 1G
    pids_limit: '256'
    cpus: '1'
    healthcheck: curl -fsS http://127.0.0.1:9696/ >/dev/null || exit 1
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Prowlarr service
