---
- name: Ensure Sonarr directory exists
  ansible.builtin.file:
    path: /mnt/fast/sonarr/config
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Sonarr image is present
  containers.podman.podman_image:
    name: lscr.io/linuxserver/sonarr:latest
    state: present
    pull: true
  notify: Restart Sonarr service

- name: Ensure Sonarr Quadlet is defined
  containers.podman.podman_container:
    name: sonarr
    state: quadlet
    image: lscr.io/linuxserver/sonarr:latest
    label:
      io.containers.autoupdate: registry
    memory: 1G
    pids_limit: '256'
    cpus: '2'
    env:
      TZ: Europe/Tallinn
    userns: keep-id:uid=1000,gid=1000
    read_only: true
    security_opt:
      - no-new-privileges
    mount:
      - type=tmpfs,destination=/run,U=true,exec
      - type=tmpfs,destination=/tmp,U=true,exec
      - type=tmpfs,destination=/var/tmp,U=true,exec
    volume:
      - /mnt/fast/sonarr/config:/config
      - /mnt/slow:/data
    network:
      - proxy.network
    healthcheck: curl -fsS http://127.0.0.1:8989/ >/dev/null || exit 1
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
    user: 1000:1000
    restart_policy: always
  notify: Restart Sonarr service
