---
- name: Ensure Beszel Agent directory exists
  ansible.builtin.file:
    path: /mnt/fast/beszel-agent/data
    state: directory
    owner: core
    group: core
    mode: '0700'

- name: Ensure Beszel Agent secrets are present
  containers.podman.podman_secret:
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    state: present
    force: true
  loop:
    - name: beszel_agent_token
      data: '{{ beszel_agent_token }}'
    - name: beszel_agent_key
      data: '{{ beszel_agent_key }}'
  loop_control:
    label: '{{ item.name }}'
  no_log: true
  notify: Restart Beszel Agent service

- name: Ensure Beszel Agent image is present
  containers.podman.podman_image:
    name: docker.io/henrygd/beszel-agent:latest
    state: present
    pull: true
  notify: Restart Beszel Agent service

- name: Ensure Beszel Agent Quadlet is defined
  containers.podman.podman_container:
    name: beszel-agent
    state: quadlet
    image: docker.io/henrygd/beszel-agent:latest
    env:
      # ALL_PROXY: ''
      # DATA_DIR: ''
      DISABLE_SSH: true
      # DISK_USAGE_CACHE: 5m
      # DOCKER_HOST: ''
      # DOCKER_TIMEOUT: 2100ms
      # EXCLUDE_CONTAINERS: ''
      # EXCLUDE_SMART: ''
      # EXIT_ON_DNS_ERROR: false
      # EXTRA_FILESYSTEMS: ''
      # FILESYSTEM: ''
      # GPU_COLLECTOR: ''
      HUB_URL: https://beszel.cormo-tegu.ts.net
      # INTEL_GPU_DEVICE: ''
      KEY_FILE: /run/secrets/beszel_agent_key
      # LHM: false
      LISTEN: 45876
      # LOG_LEVEL: info
      # MEM_CALC: ''
      # NETWORK: ''
      # NICS: ''
      # NVML: ''
      # PRIMARY_SENSOR: ''
      # SENSORS: ''
      # SENSORS_TIMEOUT: 2s
      # SERVICE_PATTERNS: ''
      # SKIP_GPU: false
      # SKIP_SYSTEMD: false
      # SMART_DEVICES: ''
      # SMART_DEVICES_SEPARATOR: ','
      # SMART_INTERVAL: 1h
      # SYS_SENSORS: ''
      # SYSTEM_NAME: 'hl01'
      TOKEN_FILE: /run/secrets/beszel_agent_token
    secrets:
      - beszel_agent_token,type=mount,target=/run/secrets/beszel_agent_token,uid=1000,gid=1000,mode=0400
      - beszel_agent_key,type=mount,target=/run/secrets/beszel_agent_key,uid=1000,gid=1000,mode=0400
    label:
      io.containers.autoupdate: registry
    network:
      - host
    volume:
      - /mnt/fast/beszel-agent/data:/var/lib/beszel-agent
      - '%t/podman/podman.sock:/var/run/docker.sock:ro'
    user: 1000:1000
    userns: keep-id:uid=1000,gid=1000
    security_opt:
      - no-new-privileges
      - label=disable
    memory: 512M
    pids_limit: '256'
    cpus: '1'
    healthcheck: CMD /agent health
    restart_policy: always
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
  notify: Restart Beszel Agent service
