---
- name: Ensure proxy network Quadlet is defined
  containers.podman.podman_network:
    name: proxy
    state: quadlet
  notify: Restart proxy network service

- name: Ensure authentication with container registries
  containers.podman.podman_login:
    registry: "{{ item.registry }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    authfile: /home/core/.config/containers/auth.json
  loop: "{{ common_registry_credentials }}"
  loop_control:
    label: "{{ item.registry }}"
  no_log: true
