---
- name: Ensure Beszel directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    owner: core
    group: core
    mode: '0700'
  loop:
    - /mnt/fast/beszel/data

- name: Ensure Beszel secrets are present
  containers.podman.podman_secret:
    name: '{{ item.name }}'
    data: '{{ item.data }}'
    state: present
    force: true
  loop:
    - name: beszel_auto_login
      data: '{{ beszel_auto_login }}'
    - name: beszel_user_email
      data: '{{ beszel_user_email }}'
    - name: beszel_user_password
      data: '{{ beszel_user_password }}'
    - name: beszel_heartbeat_url
      data: '{{ beszel_heartbeat_url }}'
  loop_control:
    label: '{{ item.name }}'
  no_log: true
  notify: Restart Beszel service

- name: Ensure Beszel image is present
  containers.podman.podman_image:
    name: docker.io/henrygd/beszel:latest
    state: present
    pull: true
  notify: Restart Beszel service

- name: Ensure Beszel Quadlet is defined
  containers.podman.podman_container:
    name: beszel
    state: quadlet
    image: docker.io/henrygd/beszel:latest
    label:
      io.containers.autoupdate: registry
    memory: 1G
    pids_limit: '256'
    cpus: '1'
    env:
      APP_URL: https://beszel.cormo-tegu.ts.net
      CHECK_UPDATES: true
      # CONTAINER_DETAILS: true
      # CSP: ''
      # DISABLE_PASSWORD_AUTH: false
      # HEARTBEAT_INTERVAL: 60
      # HEARTBEAT_METHOD: POST
      # MFA_OTP: true
      # OAUTH_DISABLE_POPUP: false
      # SHARE_ALL_SYSTEMS: false
      # TRUSTED_AUTH_HEADER: ''
      USER_CREATION: true
    secrets:
      - beszel_auto_login,type=env,target=AUTO_LOGIN
      - beszel_user_email,type=env,target=USER_EMAIL
      - beszel_user_password,type=env,target=USER_PASSWORD
      - beszel_heartbeat_url,type=env,target=HEARTBEAT_URL
    userns: keep-id:uid=1000,gid=1000
    read_only: true
    security_opt:
      - no-new-privileges
    volume:
      - /mnt/fast/beszel/data:/beszel_data
    network:
      - proxy.network
    healthcheck: /beszel health --url http://localhost:8090
    quadlet_options:
      - |
        [Install]
        WantedBy=default.target
    user: 1000:1000
    restart_policy: always
  notify: Restart Beszel service
